#!/bin/bash

# INSTALL_LOCATION="${INSTALL_LOCATION:-$(pwd)}"
# STACK_HOME="${STACK_HOME:-$(pwd)}"
INSTALL_LOCATION=~/.local/share
STACK_HOME=$INSTALL_LOCATION/stack
DEFAULT_MASTER_BIASES=~/.local/share/stack/masters
SCRIPTS_DIR=$STACK_HOME/scripts

ARGS=$(getopt \
    --options 'l:p:B:b:D:d:F:f::gjvn' \
    --longoptions 'master-biases-dir:,help,process-dir:,master-bias:,biases:master-dark:,lights:,darks:,master-flat:,flats:,lang::,no-flats,no-darks,no-biases,no-verify,verbose,remove-green,jpeg' \
    -- "${@}"\
) || exit

eval "set -- ${ARGS}"

MASTER_BIASES_DIR=$DEFAULT_MASTER_BIASES

while true; do
    case "${1}" in
        (-g | --remove-green)
            ((REMOVE_GREEN++))
            shift
        ;;
        (-j | --jpeg)
            ((RENDER_JPEG++))
            shift
        ;;
        (-v | --verbose)
            ((VERBOSE++))
            shift
        ;;
        (-n | --no-verify)
            ((NOVERIFY++))
            shift
        ;;
        (--no-flats)
            ((NO_FLATS++))
            shift
        ;;
        (--no-biases)
            ((NO_BIASES++))
            shift
        ;;
        (--no-darks)
            ((NO_DARKS++))
            shift
        ;;
        (--help)
            . ./scripts/util/help.sh && exit 1
        ;;
        (--master-biases-dir)
            MASTER_BIASES_DIR="${2}"
            shift 2
        ;;
        (-p | --process-dir)
            PROCESS_DIR="${2}"
            shift 2
        ;;
        (-l | --lights)
            LIGHTS_PATH="${2}"
            shift 2
        ;;
        (-B | --master-bias)
            MASTER_BIAS_FILE="${2}"
            shift 2
        ;;
        (-b | --biases)
            BIASES_PATH="${2}"
            shift 2
        ;;
        (-D | --master-dark)
            MASTER_DARK_FILE="${2}"
            shift 2
        ;;
        (-d | --darks)
            DARKS_PATH="${2}"
            shift 2
        ;;
        (-F | --master-flat)
            MASTER_FLAT_FILE="${2}"
            shift 2
        ;;
        (-f | --flats)
            FLATS_PATH="${2}"
            shift 2
        ;;
        # (-l | --lang | --language)
        #     # handle optional: getopt normalizes it into an empty string
        #     if [ -n "${2}" ] ; then
        #         LANG="${2}"
        #     fi
        #     shift 2
        # ;;
        (--)
            shift
            break
        ;;
        (*)
            exit 1    # error
        ;;
    esac
done
shift $((OPTIND-1))

WORKING_DIRECTORY=$(realpath "${@:-$(pwd)}")

PROCESS_DIR=${PROCESS_DIR:="$WORKING_DIRECTORY/process"}
BIASES_PATH=${BIASES_PATH:="$MASTER_BIASES_DIR"}
DARKS_PATH=${DARKS_PATH:="$WORKING_DIRECTORY/darks"}
FLATS_PATH=${FLATS_PATH:="$WORKING_DIRECTORY/flats"}
LIGHTS_PATH=${LIGHTS_PATH:="$WORKING_DIRECTORY/lights"}

function verboseOutput() {
echo "WORKING_DIRECTORY: "$WORKING_DIRECTORY
echo "PROCESS_DIR: "$PROCESS_DIR
echo "MASTER_BIASES_DIR: "$MASTER_BIASES_DIR
echo ''
echo "LIGHTS_PATH: "$LIGHTS_PATH
echo "MASTER_BIAS_FILE: "$MASTER_BIAS_FILE
echo "BIASES_PATH: "$BIASES_PATH
echo "MASTER_DARK_FILE: "$MASTER_DARK_FILE
echo "DARKS_PATH: "$DARKS_PATH
echo "MASTER_FLAT_FILE: "$MASTER_FLAT_FILE
echo "FLATS_PATH: "$FLATS_PATH
echo ''
echo "NO_FLATS: "$NO_FLATS
echo "NO_DARKS: "$NO_DARKS
echo "NO_BIASES: "$NO_BIASES
echo ''
echo "RENDER_JPEG: "$RENDER_JPEG
echo "REMOVE_GREEN: "$REMOVE_GREEN
}

if [[ "$VERBOSE" == 1 ]]; then
    verboseOutput;
fi;

. $SCRIPTS_DIR/start.sh